---
- name: Configure EC2 instance
  hosts: api
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: dist
      register: apt_update
      failed_when: apt_update is failed
      ignore_errors: yes

    - name: Debug apt update
      debug:
        var: apt_update

    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: Add Docker repository
      run: sudo add-apt-repository "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: Update apt packages
      run: sudo apt-get update

    - name: Install Docker
      run: sudo apt install -y docker-ce docker-ce-cli containerd.io
    
    - name: enable Docker
      run: sudo systemctl enable docker
    
    - name: enable containerd
      run: sudo systemctl enable containerd
    
    - name: verify installation
      run: sudo systemctl status docker
    
    - name: Add user to Docker group
      run: sudo usermod -aG docker $USER

    - name: Restart terminal to apply changes
      run: newgrp docker